# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorder_double.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ESAIMU_RecorderUI(object):
    def setupUi(self, ESAIMU_RecorderUI):
        ESAIMU_RecorderUI.setObjectName("ESAIMU_RecorderUI")
        ESAIMU_RecorderUI.resize(849, 646)
        self.centralwidget = QtWidgets.QWidget(ESAIMU_RecorderUI)
        self.centralwidget.setObjectName("centralwidget")
        self.ComPortSelect = QtWidgets.QComboBox(self.centralwidget)
        self.ComPortSelect.setGeometry(QtCore.QRect(110, 40, 161, 22))
        self.ComPortSelect.setObjectName("ComPortSelect")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(280, 70, 75, 23))
        self.ConnectButton.setObjectName("ConnectButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 500, 81, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.SavePath = QtWidgets.QLineEdit(self.centralwidget)
        self.SavePath.setGeometry(QtCore.QRect(350, 500, 161, 20))
        self.SavePath.setObjectName("SavePath")
        self.BrowseSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseSaveButton.setGeometry(QtCore.QRect(520, 500, 75, 23))
        self.BrowseSaveButton.setObjectName("BrowseSaveButton")
        self.checkWriteRaw = QtWidgets.QCheckBox(self.centralwidget)
        self.checkWriteRaw.setGeometry(QtCore.QRect(280, 560, 111, 16))
        self.checkWriteRaw.setObjectName("checkWriteRaw")
        self.BrowseOffsetButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseOffsetButton.setGeometry(QtCore.QRect(280, 150, 75, 23))
        self.BrowseOffsetButton.setObjectName("BrowseOffsetButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.OffsetPath = QtWidgets.QLineEdit(self.centralwidget)
        self.OffsetPath.setGeometry(QtCore.QRect(110, 150, 161, 20))
        self.OffsetPath.setObjectName("OffsetPath")
        self.StatusText = QtWidgets.QLabel(self.centralwidget)
        self.StatusText.setGeometry(QtCore.QRect(30, 230, 341, 16))
        self.StatusText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StatusText.setObjectName("StatusText")
        self.ax = QtWidgets.QLineEdit(self.centralwidget)
        self.ax.setGeometry(QtCore.QRect(30, 310, 113, 20))
        self.ax.setObjectName("ax")
        self.ay = QtWidgets.QLineEdit(self.centralwidget)
        self.ay.setGeometry(QtCore.QRect(150, 310, 113, 20))
        self.ay.setObjectName("ay")
        self.az = QtWidgets.QLineEdit(self.centralwidget)
        self.az.setGeometry(QtCore.QRect(270, 310, 113, 20))
        self.az.setObjectName("az")
        self.gy = QtWidgets.QLineEdit(self.centralwidget)
        self.gy.setGeometry(QtCore.QRect(150, 360, 113, 20))
        self.gy.setObjectName("gy")
        self.gz = QtWidgets.QLineEdit(self.centralwidget)
        self.gz.setGeometry(QtCore.QRect(270, 360, 113, 20))
        self.gz.setObjectName("gz")
        self.gx = QtWidgets.QLineEdit(self.centralwidget)
        self.gx.setGeometry(QtCore.QRect(30, 360, 113, 20))
        self.gx.setObjectName("gx")
        self.mz = QtWidgets.QLineEdit(self.centralwidget)
        self.mz.setGeometry(QtCore.QRect(270, 410, 113, 20))
        self.mz.setObjectName("mz")
        self.my = QtWidgets.QLineEdit(self.centralwidget)
        self.my.setGeometry(QtCore.QRect(150, 410, 113, 20))
        self.my.setObjectName("my")
        self.mx = QtWidgets.QLineEdit(self.centralwidget)
        self.mx.setGeometry(QtCore.QRect(30, 410, 113, 20))
        self.mx.setObjectName("mx")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 290, 47, 12))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 340, 47, 12))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 390, 47, 12))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.RecordButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecordButton.setGeometry(QtCore.QRect(520, 550, 75, 23))
        self.RecordButton.setObjectName("RecordButton")
        self.radioLoadOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLoadOffset.setGeometry(QtCore.QRect(50, 100, 141, 16))
        self.radioLoadOffset.setObjectName("radioLoadOffset")
        self.buttonGroup = QtWidgets.QButtonGroup(ESAIMU_RecorderUI)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioLoadOffset)
        self.radioSaveOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSaveOffset.setGeometry(QtCore.QRect(200, 100, 111, 16))
        self.radioSaveOffset.setObjectName("radioSaveOffset")
        self.buttonGroup.addButton(self.radioSaveOffset)
        self.radioNoOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioNoOffset.setGeometry(QtCore.QRect(200, 120, 111, 16))
        self.radioNoOffset.setObjectName("radioNoOffset")
        self.buttonGroup.addButton(self.radioNoOffset)
        self.radioOneTimeOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioOneTimeOffset.setGeometry(QtCore.QRect(50, 120, 141, 16))
        self.radioOneTimeOffset.setChecked(True)
        self.radioOneTimeOffset.setAutoExclusive(True)
        self.radioOneTimeOffset.setObjectName("radioOneTimeOffset")
        self.buttonGroup.addButton(self.radioOneTimeOffset)
        self.ReceivedLabel = QtWidgets.QLabel(self.centralwidget)
        self.ReceivedLabel.setGeometry(QtCore.QRect(30, 260, 91, 16))
        self.ReceivedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ReceivedLabel.setObjectName("ReceivedLabel")
        self.ReceivedNumber = QtWidgets.QLabel(self.centralwidget)
        self.ReceivedNumber.setGeometry(QtCore.QRect(130, 260, 101, 16))
        self.ReceivedNumber.setText("")
        self.ReceivedNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ReceivedNumber.setObjectName("ReceivedNumber")
        self.checkUseTimer = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUseTimer.setGeometry(QtCore.QRect(390, 560, 111, 16))
        self.checkUseTimer.setObjectName("checkUseTimer")
        self.RecordedLabel = QtWidgets.QLabel(self.centralwidget)
        self.RecordedLabel.setGeometry(QtCore.QRect(280, 600, 91, 16))
        self.RecordedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RecordedLabel.setObjectName("RecordedLabel")
        self.RecordTime = QtWidgets.QLabel(self.centralwidget)
        self.RecordTime.setGeometry(QtCore.QRect(390, 600, 101, 16))
        self.RecordTime.setText("")
        self.RecordTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RecordTime.setObjectName("RecordTime")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 530, 81, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.PacketSizeSelect = QtWidgets.QComboBox(self.centralwidget)
        self.PacketSizeSelect.setGeometry(QtCore.QRect(110, 70, 161, 22))
        self.PacketSizeSelect.setObjectName("PacketSizeSelect")
        self.PacketSizeSelect.addItem("")
        self.PacketSizeSelect.addItem("")
        self.RecordingTimeInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.RecordingTimeInput.setGeometry(QtCore.QRect(370, 530, 111, 22))
        self.RecordingTimeInput.setMaximum(60000.0)
        self.RecordingTimeInput.setObjectName("RecordingTimeInput")
        self.ReceivedLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ReceivedLabel_2.setGeometry(QtCore.QRect(470, 260, 91, 16))
        self.ReceivedLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ReceivedLabel_2.setObjectName("ReceivedLabel_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 290, 47, 12))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(620, 340, 47, 12))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(470, 40, 71, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.ax_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ax_2.setGeometry(QtCore.QRect(470, 310, 113, 20))
        self.ax_2.setObjectName("ax_2")
        self.radioOneTimeOffset_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioOneTimeOffset_2.setGeometry(QtCore.QRect(490, 120, 141, 16))
        self.radioOneTimeOffset_2.setChecked(True)
        self.radioOneTimeOffset_2.setAutoExclusive(True)
        self.radioOneTimeOffset_2.setObjectName("radioOneTimeOffset_2")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(ESAIMU_RecorderUI)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioOneTimeOffset_2)
        self.PacketSizeSelect_2 = QtWidgets.QComboBox(self.centralwidget)
        self.PacketSizeSelect_2.setGeometry(QtCore.QRect(550, 70, 161, 22))
        self.PacketSizeSelect_2.setObjectName("PacketSizeSelect_2")
        self.PacketSizeSelect_2.addItem("")
        self.PacketSizeSelect_2.addItem("")
        self.az_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.az_2.setGeometry(QtCore.QRect(710, 310, 113, 20))
        self.az_2.setObjectName("az_2")
        self.BrowseOffsetButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseOffsetButton_2.setGeometry(QtCore.QRect(720, 150, 75, 23))
        self.BrowseOffsetButton_2.setObjectName("BrowseOffsetButton_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(620, 390, 47, 12))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.ReceivedNumber_2 = QtWidgets.QLabel(self.centralwidget)
        self.ReceivedNumber_2.setGeometry(QtCore.QRect(570, 260, 101, 16))
        self.ReceivedNumber_2.setText("")
        self.ReceivedNumber_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ReceivedNumber_2.setObjectName("ReceivedNumber_2")
        self.radioSaveOffset_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSaveOffset_2.setGeometry(QtCore.QRect(640, 100, 111, 16))
        self.radioSaveOffset_2.setAutoExclusive(True)
        self.radioSaveOffset_2.setObjectName("radioSaveOffset_2")
        self.buttonGroup_2.addButton(self.radioSaveOffset_2)
        self.gx_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.gx_2.setGeometry(QtCore.QRect(470, 360, 113, 20))
        self.gx_2.setObjectName("gx_2")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(470, 70, 71, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gz_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.gz_2.setGeometry(QtCore.QRect(710, 360, 113, 20))
        self.gz_2.setObjectName("gz_2")
        self.radioNoOffset_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioNoOffset_2.setGeometry(QtCore.QRect(640, 120, 111, 16))
        self.radioNoOffset_2.setAutoExclusive(True)
        self.radioNoOffset_2.setObjectName("radioNoOffset_2")
        self.buttonGroup_2.addButton(self.radioNoOffset_2)
        self.mz_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.mz_2.setGeometry(QtCore.QRect(710, 410, 113, 20))
        self.mz_2.setObjectName("mz_2")
        self.StatusText_2 = QtWidgets.QLabel(self.centralwidget)
        self.StatusText_2.setGeometry(QtCore.QRect(470, 230, 341, 16))
        self.StatusText_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StatusText_2.setObjectName("StatusText_2")
        self.ay_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ay_2.setGeometry(QtCore.QRect(590, 310, 113, 20))
        self.ay_2.setObjectName("ay_2")
        self.my_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.my_2.setGeometry(QtCore.QRect(590, 410, 113, 20))
        self.my_2.setObjectName("my_2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(450, 150, 91, 16))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.ConnectButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton_2.setGeometry(QtCore.QRect(720, 70, 75, 23))
        self.ConnectButton_2.setObjectName("ConnectButton_2")
        self.radioLoadOffset_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLoadOffset_2.setGeometry(QtCore.QRect(490, 100, 141, 16))
        self.radioLoadOffset_2.setAutoExclusive(True)
        self.radioLoadOffset_2.setObjectName("radioLoadOffset_2")
        self.buttonGroup_2.addButton(self.radioLoadOffset_2)
        self.ComPortSelect_2 = QtWidgets.QComboBox(self.centralwidget)
        self.ComPortSelect_2.setGeometry(QtCore.QRect(550, 40, 161, 22))
        self.ComPortSelect_2.setObjectName("ComPortSelect_2")
        self.gy_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.gy_2.setGeometry(QtCore.QRect(590, 360, 113, 20))
        self.gy_2.setObjectName("gy_2")
        self.OffsetPath_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.OffsetPath_2.setGeometry(QtCore.QRect(550, 150, 161, 20))
        self.OffsetPath_2.setObjectName("OffsetPath_2")
        self.mx_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.mx_2.setGeometry(QtCore.QRect(470, 410, 113, 20))
        self.mx_2.setObjectName("mx_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(150, 10, 71, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(590, 10, 71, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.StatusText_6 = QtWidgets.QLabel(self.centralwidget)
        self.StatusText_6.setGeometry(QtCore.QRect(380, 470, 91, 16))
        self.StatusText_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StatusText_6.setObjectName("StatusText_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 450, 811, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(410, 20, 20, 421))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        ESAIMU_RecorderUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ESAIMU_RecorderUI)
        self.statusbar.setObjectName("statusbar")
        ESAIMU_RecorderUI.setStatusBar(self.statusbar)

        self.retranslateUi(ESAIMU_RecorderUI)
        QtCore.QMetaObject.connectSlotsByName(ESAIMU_RecorderUI)

    def retranslateUi(self, ESAIMU_RecorderUI):
        _translate = QtCore.QCoreApplication.translate
        ESAIMU_RecorderUI.setWindowTitle(_translate("ESAIMU_RecorderUI", "IMU Recorder"))
        self.ConnectButton.setText(_translate("ESAIMU_RecorderUI", "Connect"))
        self.label.setText(_translate("ESAIMU_RecorderUI", "COM Port"))
        self.label_2.setText(_translate("ESAIMU_RecorderUI", "Save Location"))
        self.BrowseSaveButton.setText(_translate("ESAIMU_RecorderUI", "Browse"))
        self.checkWriteRaw.setText(_translate("ESAIMU_RecorderUI", "Write Raw Data"))
        self.BrowseOffsetButton.setText(_translate("ESAIMU_RecorderUI", "Browse"))
        self.label_3.setText(_translate("ESAIMU_RecorderUI", "Offset File"))
        self.StatusText.setText(_translate("ESAIMU_RecorderUI", "Disconnected"))
        self.label_5.setText(_translate("ESAIMU_RecorderUI", "Acc"))
        self.label_6.setText(_translate("ESAIMU_RecorderUI", "Gyro"))
        self.label_7.setText(_translate("ESAIMU_RecorderUI", "Mag"))
        self.RecordButton.setText(_translate("ESAIMU_RecorderUI", "Record"))
        self.radioLoadOffset.setText(_translate("ESAIMU_RecorderUI", "Load Offset"))
        self.radioSaveOffset.setText(_translate("ESAIMU_RecorderUI", "Save Offset"))
        self.radioNoOffset.setText(_translate("ESAIMU_RecorderUI", "Disable Offset"))
        self.radioOneTimeOffset.setText(_translate("ESAIMU_RecorderUI", "One-Time Offset"))
        self.ReceivedLabel.setText(_translate("ESAIMU_RecorderUI", "Received: "))
        self.checkUseTimer.setText(_translate("ESAIMU_RecorderUI", "Use Timer"))
        self.RecordedLabel.setText(_translate("ESAIMU_RecorderUI", "Recorded:"))
        self.label_4.setText(_translate("ESAIMU_RecorderUI", "Record Time (s)"))
        self.label_8.setText(_translate("ESAIMU_RecorderUI", "Packet Size"))
        self.PacketSizeSelect.setItemText(0, _translate("ESAIMU_RecorderUI", "36"))
        self.PacketSizeSelect.setItemText(1, _translate("ESAIMU_RecorderUI", "342"))
        self.ReceivedLabel_2.setText(_translate("ESAIMU_RecorderUI", "Received: "))
        self.label_9.setText(_translate("ESAIMU_RecorderUI", "Acc"))
        self.label_11.setText(_translate("ESAIMU_RecorderUI", "Gyro"))
        self.label_12.setText(_translate("ESAIMU_RecorderUI", "COM Port"))
        self.radioOneTimeOffset_2.setText(_translate("ESAIMU_RecorderUI", "One-Time Offset"))
        self.PacketSizeSelect_2.setItemText(0, _translate("ESAIMU_RecorderUI", "36"))
        self.PacketSizeSelect_2.setItemText(1, _translate("ESAIMU_RecorderUI", "342"))
        self.BrowseOffsetButton_2.setText(_translate("ESAIMU_RecorderUI", "Browse"))
        self.label_13.setText(_translate("ESAIMU_RecorderUI", "Mag"))
        self.radioSaveOffset_2.setText(_translate("ESAIMU_RecorderUI", "Save Offset"))
        self.label_14.setText(_translate("ESAIMU_RecorderUI", "Packet Size"))
        self.radioNoOffset_2.setText(_translate("ESAIMU_RecorderUI", "Disable Offset"))
        self.StatusText_2.setText(_translate("ESAIMU_RecorderUI", "Disconnected"))
        self.label_16.setText(_translate("ESAIMU_RecorderUI", "Offset File"))
        self.ConnectButton_2.setText(_translate("ESAIMU_RecorderUI", "Connect"))
        self.radioLoadOffset_2.setText(_translate("ESAIMU_RecorderUI", "Load Offset"))
        self.label_15.setText(_translate("ESAIMU_RecorderUI", "IMU1"))
        self.label_17.setText(_translate("ESAIMU_RecorderUI", "IMU2"))
        self.StatusText_6.setText(_translate("ESAIMU_RecorderUI", "Record IMU"))

