# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorder_single.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ESAIMU_RecorderUI(object):
    def setupUi(self, ESAIMU_RecorderUI):
        ESAIMU_RecorderUI.setObjectName("ESAIMU_RecorderUI")
        ESAIMU_RecorderUI.resize(387, 491)
        self.centralwidget = QtWidgets.QWidget(ESAIMU_RecorderUI)
        self.centralwidget.setObjectName("centralwidget")
        self.ComPortSelect = QtWidgets.QComboBox(self.centralwidget)
        self.ComPortSelect.setGeometry(QtCore.QRect(100, 10, 161, 22))
        self.ComPortSelect.setObjectName("ComPortSelect")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(270, 40, 75, 23))
        self.ConnectButton.setObjectName("ConnectButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.SavePath = QtWidgets.QLineEdit(self.centralwidget)
        self.SavePath.setGeometry(QtCore.QRect(100, 150, 161, 20))
        self.SavePath.setObjectName("SavePath")
        self.BrowseSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseSaveButton.setGeometry(QtCore.QRect(270, 150, 75, 23))
        self.BrowseSaveButton.setObjectName("BrowseSaveButton")
        self.checkWriteRaw = QtWidgets.QCheckBox(self.centralwidget)
        self.checkWriteRaw.setGeometry(QtCore.QRect(100, 180, 111, 16))
        self.checkWriteRaw.setObjectName("checkWriteRaw")
        self.BrowseOffsetButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseOffsetButton.setGeometry(QtCore.QRect(270, 120, 75, 23))
        self.BrowseOffsetButton.setObjectName("BrowseOffsetButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 91, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.OffsetPath = QtWidgets.QLineEdit(self.centralwidget)
        self.OffsetPath.setGeometry(QtCore.QRect(100, 120, 161, 20))
        self.OffsetPath.setObjectName("OffsetPath")
        self.StatusText = QtWidgets.QLabel(self.centralwidget)
        self.StatusText.setGeometry(QtCore.QRect(10, 240, 341, 16))
        self.StatusText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StatusText.setObjectName("StatusText")
        self.ax = QtWidgets.QLineEdit(self.centralwidget)
        self.ax.setGeometry(QtCore.QRect(10, 340, 113, 20))
        self.ax.setObjectName("ax")
        self.ay = QtWidgets.QLineEdit(self.centralwidget)
        self.ay.setGeometry(QtCore.QRect(130, 340, 113, 20))
        self.ay.setObjectName("ay")
        self.az = QtWidgets.QLineEdit(self.centralwidget)
        self.az.setGeometry(QtCore.QRect(250, 340, 113, 20))
        self.az.setObjectName("az")
        self.gy = QtWidgets.QLineEdit(self.centralwidget)
        self.gy.setGeometry(QtCore.QRect(130, 390, 113, 20))
        self.gy.setObjectName("gy")
        self.gz = QtWidgets.QLineEdit(self.centralwidget)
        self.gz.setGeometry(QtCore.QRect(250, 390, 113, 20))
        self.gz.setObjectName("gz")
        self.gx = QtWidgets.QLineEdit(self.centralwidget)
        self.gx.setGeometry(QtCore.QRect(10, 390, 113, 20))
        self.gx.setObjectName("gx")
        self.mz = QtWidgets.QLineEdit(self.centralwidget)
        self.mz.setGeometry(QtCore.QRect(250, 440, 113, 20))
        self.mz.setObjectName("mz")
        self.my = QtWidgets.QLineEdit(self.centralwidget)
        self.my.setGeometry(QtCore.QRect(130, 440, 113, 20))
        self.my.setObjectName("my")
        self.mx = QtWidgets.QLineEdit(self.centralwidget)
        self.mx.setGeometry(QtCore.QRect(10, 440, 113, 20))
        self.mx.setObjectName("mx")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 320, 47, 12))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 370, 47, 12))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 420, 47, 12))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.RecordButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecordButton.setGeometry(QtCore.QRect(270, 200, 75, 23))
        self.RecordButton.setObjectName("RecordButton")
        self.radioLoadOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLoadOffset.setGeometry(QtCore.QRect(70, 70, 141, 16))
        self.radioLoadOffset.setObjectName("radioLoadOffset")
        self.radioSaveOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSaveOffset.setGeometry(QtCore.QRect(220, 70, 111, 16))
        self.radioSaveOffset.setObjectName("radioSaveOffset")
        self.radioNoOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioNoOffset.setGeometry(QtCore.QRect(220, 90, 111, 16))
        self.radioNoOffset.setObjectName("radioNoOffset")
        self.radioOneTimeOffset = QtWidgets.QRadioButton(self.centralwidget)
        self.radioOneTimeOffset.setGeometry(QtCore.QRect(70, 90, 141, 16))
        self.radioOneTimeOffset.setChecked(True)
        self.radioOneTimeOffset.setObjectName("radioOneTimeOffset")
        self.StatusText_2 = QtWidgets.QLabel(self.centralwidget)
        self.StatusText_2.setGeometry(QtCore.QRect(10, 270, 91, 16))
        self.StatusText_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StatusText_2.setObjectName("StatusText_2")
        self.ReceivedNumber = QtWidgets.QLabel(self.centralwidget)
        self.ReceivedNumber.setGeometry(QtCore.QRect(110, 270, 101, 16))
        self.ReceivedNumber.setText("")
        self.ReceivedNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ReceivedNumber.setObjectName("ReceivedNumber")
        self.checkUseTimer = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUseTimer.setGeometry(QtCore.QRect(220, 180, 111, 16))
        self.checkUseTimer.setObjectName("checkUseTimer")
        self.StatusText_3 = QtWidgets.QLabel(self.centralwidget)
        self.StatusText_3.setGeometry(QtCore.QRect(10, 290, 91, 16))
        self.StatusText_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.StatusText_3.setObjectName("StatusText_3")
        self.RecordTime = QtWidgets.QLabel(self.centralwidget)
        self.RecordTime.setGeometry(QtCore.QRect(110, 290, 101, 16))
        self.RecordTime.setText("")
        self.RecordTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RecordTime.setObjectName("RecordTime")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.PacketSizeSelect = QtWidgets.QComboBox(self.centralwidget)
        self.PacketSizeSelect.setGeometry(QtCore.QRect(100, 40, 161, 22))
        self.PacketSizeSelect.setObjectName("PacketSizeSelect")
        self.PacketSizeSelect.addItem("")
        self.PacketSizeSelect.addItem("")
        self.RecordingTimeInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.RecordingTimeInput.setGeometry(QtCore.QRect(100, 200, 161, 22))
        self.RecordingTimeInput.setObjectName("RecordingTimeInput")
        ESAIMU_RecorderUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ESAIMU_RecorderUI)
        self.statusbar.setObjectName("statusbar")
        ESAIMU_RecorderUI.setStatusBar(self.statusbar)

        self.retranslateUi(ESAIMU_RecorderUI)
        QtCore.QMetaObject.connectSlotsByName(ESAIMU_RecorderUI)

    def retranslateUi(self, ESAIMU_RecorderUI):
        _translate = QtCore.QCoreApplication.translate
        ESAIMU_RecorderUI.setWindowTitle(_translate("ESAIMU_RecorderUI", "IMU Recorder"))
        self.ConnectButton.setText(_translate("ESAIMU_RecorderUI", "Connect"))
        self.label.setText(_translate("ESAIMU_RecorderUI", "COM Port"))
        self.label_2.setText(_translate("ESAIMU_RecorderUI", "Save Location"))
        self.BrowseSaveButton.setText(_translate("ESAIMU_RecorderUI", "Browse"))
        self.checkWriteRaw.setText(_translate("ESAIMU_RecorderUI", "Write Raw Data"))
        self.BrowseOffsetButton.setText(_translate("ESAIMU_RecorderUI", "Browse"))
        self.label_3.setText(_translate("ESAIMU_RecorderUI", "Offset File"))
        self.StatusText.setText(_translate("ESAIMU_RecorderUI", "Disconnected"))
        self.label_5.setText(_translate("ESAIMU_RecorderUI", "Acc"))
        self.label_6.setText(_translate("ESAIMU_RecorderUI", "Gyro"))
        self.label_7.setText(_translate("ESAIMU_RecorderUI", "Mag"))
        self.RecordButton.setText(_translate("ESAIMU_RecorderUI", "Record"))
        self.radioLoadOffset.setText(_translate("ESAIMU_RecorderUI", "Load Offset"))
        self.radioSaveOffset.setText(_translate("ESAIMU_RecorderUI", "Save Offset"))
        self.radioNoOffset.setText(_translate("ESAIMU_RecorderUI", "Disable Offset"))
        self.radioOneTimeOffset.setText(_translate("ESAIMU_RecorderUI", "One-Time Offset"))
        self.StatusText_2.setText(_translate("ESAIMU_RecorderUI", "Received: "))
        self.checkUseTimer.setText(_translate("ESAIMU_RecorderUI", "Use Timer"))
        self.StatusText_3.setText(_translate("ESAIMU_RecorderUI", "Recorded:"))
        self.label_4.setText(_translate("ESAIMU_RecorderUI", "Time (s)"))
        self.label_8.setText(_translate("ESAIMU_RecorderUI", "Packet Size"))
        self.PacketSizeSelect.setItemText(0, _translate("ESAIMU_RecorderUI", "36"))
        self.PacketSizeSelect.setItemText(1, _translate("ESAIMU_RecorderUI", "342"))

